# parsedmarc configuration template (based on docs: https://domainaware.github.io/parsedmarc/usage.html#configuration-file)

[general]
save_aggregate = True
save_forensic = True
save_smtp_tls = False
# index_prefix_domain_map = /etc/parsedmarc/tenant_domain_map.yml
strip_attachment_payloads = False
silent = True
# output = /tmp/parsedmarc-output
# aggregate_json_filename = aggregate.json
# forensic_json_filename = forensic.json
# smtp_tls_json_filename = smtp_tls.json
# aggregate_csv_filename = aggregate.csv
# forensic_csv_filename = forensic.csv
# smtp_tls_csv_filename = smtp_tls.csv
# ip_db_path = /usr/share/GeoIP/GeoLite2-City.mmdb
offline = False
always_use_local_files = False
# local_reverse_dns_map_path = /opt/parsedmarc/base_reverse_dns_map.csv
# reverse_dns_map_url = https://raw.githubusercontent.com/domainaware/parsedmarc/master/parsedmarc/resources/maps/base_reverse_dns_map.csv
# nameservers = 1.1.1.1,1.0.0.1
# dns_test_address = 1.1.1.1
dns_timeout = 2.0
debug = False
log_file = /var/log/parsedmarc/parsedmarc.log
n_procs = 4

[mailbox]
reports_folder = DMARC
archive_folder = DMARC_Archived
watch = True
delete = False
test = False
batch_size = 10
check_timeout = 30
# since = 1d

[imap]
host = imap.example.com
port = 993
ssl = True
skip_certificate_verification = False
user = parsedmarc@example.com
password = change_me

[msgraph]
# auth_method = UsernamePassword
# user = user@example.com
# password = change_me
# client_id = 00000000-0000-0000-0000-000000000000
# client_secret = change_me
# tenant_id = 00000000-0000-0000-0000-000000000000
# mailbox = reports@example.com
# graph_url = https://graph.microsoft.com
# token_file = /tokens/.token.json
# allow_unencrypted_storage = False

[elasticsearch]
hosts = es01:9200
user = elastic
password = change_me
# api_key =
ssl = True
timeout = 60
# cert_path = /etc/ssl/certs/ca-certificates.crt
# index_suffix =
# index_prefix =
monthly_indexes = False
number_of_shards = 1
number_of_replicas = 0

[opensearch]
# hosts = es01:9200
# user = admin
# password = change_me
# api_key =
# ssl = True
# timeout = 60
# cert_path = /etc/ssl/certs/ca-certificates.crt
# index_suffix =
# index_prefix =
# monthly_indexes = False
# number_of_shards = 1
# number_of_replicas = 0

[splunk_hec]
# url = https://splunkhec.example.com
# token = HECTokenGoesHere
# index = email
# skip_certificate_verification = False

[kafka]
# hosts = kafka1:9092,kafka2:9092
# user =
# password =
# NOTE: Documentation currently shows `passsword` (with 3x "s").
# passsword =
# ssl = True
# skip_certificate_verification = False
# aggregate_topic = parsedmarc_aggregate
# forensic_topic = parsedmarc_forensic

[smtp]
# host = smtp.example.com
# port = 25
# ssl = False
# skip_certificate_verification = False
# user =
# password =
# from = parsedmarc@example.com
# to = secops@example.com,postmaster@example.com
# subject = parsedmarc report
# attachment = aggregate,forensic,smtp_tls
# message = Please see the attached parsedmarc report.

[s3]
# bucket = my-bucket
# path = parsedmarc
# region_name = eu-central-1
# endpoint_url =
# access_key_id =
# secret_access_key =

[syslog]
# server = localhost
# port = 514
# protocol = udp
# cafile_path =
# certfile_path =
# keyfile_path =
# timeout = 5.0
# retry_attempts = 3
# retry_delay = 5

[gmail_api]
# credentials_file = /etc/parsedmarc/gmail-credentials.json
# token_file = /etc/parsedmarc/gmail-token.json
# include_spam_trash = False
# scopes = https://www.googleapis.com/auth/gmail.modify
# oauth2_port = 8080
# paginate_messages = True

[log_analytics]
# client_id = 00000000-0000-0000-0000-000000000000
# client_secret = change_me
# tenant_id = 00000000-0000-0000-0000-000000000000
# dce = https://<dce-name>.<region>.ingest.monitor.azure.com
# dcr_immutable_id =
# dcr_aggregate_stream =
# dcr_forensic_stream =
# dcr_smtp_tls_stream =

[gelf]
# host = logger
# port = 12201
# mode = tcp

[maildir]
# maildir_path = INBOX
# maildir_create = False

[webhook]
# aggregate_url = https://aggregate-url.example.com
# forensic_url = https://forensic-url.example.com
# smtp_tls_url = https://smtp-tls-url.example.com
# timeout = 60
